// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-template/internal"
	"gin-template/internal/conf"
	"gin-template/internal/domain"
	"gin-template/internal/domain/demo"
	"gin-template/internal/router"
	"gin-template/pkg/infra"
	"log/slog"
)

// Injectors from wire.go:

func initApp(cfg *conf.Bootstrap, logger *slog.Logger) *internal.MainApp {
	client := infra.NewRedisClient(cfg)
	redisClient := infra.NewCustomRedisClient(client)
	data := infra.NewData(cfg, redisClient)
	demoRepo := demo.NewDemoRepo(data)
	demoBiz := demo.NewDemoBiz(logger, demoRepo)
	demoService := demo.NewDemoService(demoBiz, logger)
	serviceHub := domain.NewServiceHub(demoService)
	registerFunc := router.NewRegisterFunc()
	registeredMiddleWire := router.NewRegisterMiddleWire()
	mainApp := internal.NewMainApp(cfg, serviceHub, registerFunc, registeredMiddleWire, data)
	return mainApp
}
