// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-template/internal"
	"gin-template/internal/conf"
	"gin-template/internal/domain"
	"gin-template/internal/domain/demo/biz"
	"gin-template/internal/domain/demo/data"
	"gin-template/internal/domain/demo/service"
	"gin-template/internal/router"
	"gin-template/pkg/infra"
	"log/slog"
)

// Injectors from wire.go:

func initApp(cfg *conf.Bootstrap, logger *slog.Logger) *internal.MainApp {
	client := infra.NewRedisClient(cfg)
	redisClient := infra.NewCustomRedisClient(client)
	infraData := infra.NewData(cfg, redisClient)
	demoRepo := data.NewDemoRepo(infraData)
	demoBiz := biz.NewDemoBiz(logger, demoRepo)
	demoService := service.NewDemoService(demoBiz, logger)
	serviceHub := domain.NewServiceHub(demoService)
	registerFunc := router.NewRegisterFunc()
	registeredMiddleWire := router.NewRegisterMiddleWire()
	mainApp := internal.NewMainApp(cfg, serviceHub, registerFunc, registeredMiddleWire, infraData)
	return mainApp
}
