// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap 应用配置根节点，与 config.yaml 结构一一对应。
//
// key 与字段名保持一致：protojson 同时接受「原始字段名」与 lowerCamelCase，
// 因此 YAML 里现有的 snake_case 写法（如 db_name、enable_db_debug）无需修改。
type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Data                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Server        *Server                `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Log           *Log                   `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	App           *App                   `protobuf:"bytes,4,opt,name=app,proto3" json:"app,omitempty"`
	Otel          *Otel                  `protobuf:"bytes,5,opt,name=otel,proto3" json:"otel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Bootstrap) GetApp() *App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *Bootstrap) GetOtel() *Otel {
	if x != nil {
		return x.Otel
	}
	return nil
}

// Otel 可观测性配置：一个端点同时驱动 trace / metrics / logs 三路 OTLP/HTTP 主动推送。
//
// 三类信号仅是 exporter 默认路径不同（/v1/traces、/v1/metrics、/v1/logs），
// 因此共用一个 host:port 即可；metrics_endpoint / logs_endpoint 仅作逃生口。
// endpoint 为空表示关闭全部 OTLP 上报（默认状态，安全）。
type Otel struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Endpoint               string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                                                         // OTLP/HTTP 端点：host:port 或 http(s)://host:port；空值=关闭
	Insecure               bool                   `protobuf:"varint,2,opt,name=insecure,proto3" json:"insecure,omitempty"`                                                                        // 明文传输；endpoint 带 http:// 时自动为 true
	Headers                map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外请求头（如 ingestion key，建议来自环境变量）
	ServiceName            string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`                                                // service.name，缺省为 gin-template
	ServiceVersion         string                 `protobuf:"bytes,5,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`                                       // service.version，建议由 -ldflags 注入
	Environment            string                 `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`                                                                   // deployment.environment，如 production
	TraceSampleRate        float64                `protobuf:"fixed64,7,opt,name=trace_sample_rate,json=traceSampleRate,proto3" json:"trace_sample_rate,omitempty"`                                // 采样率 0.0-1.0，0 视为 1.0
	MetricsEndpoint        string                 `protobuf:"bytes,8,opt,name=metrics_endpoint,json=metricsEndpoint,proto3" json:"metrics_endpoint,omitempty"`                                    // 可选：metrics 专用端点覆盖
	LogsEndpoint           string                 `protobuf:"bytes,9,opt,name=logs_endpoint,json=logsEndpoint,proto3" json:"logs_endpoint,omitempty"`                                             // 可选：logs 专用端点覆盖
	MetricsIntervalSeconds uint32                 `protobuf:"varint,10,opt,name=metrics_interval_seconds,json=metricsIntervalSeconds,proto3" json:"metrics_interval_seconds,omitempty"`           // 指标推送周期，0 视为 15s
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Otel) Reset() {
	*x = Otel{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Otel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Otel) ProtoMessage() {}

func (x *Otel) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Otel.ProtoReflect.Descriptor instead.
func (*Otel) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Otel) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Otel) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *Otel) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Otel) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Otel) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *Otel) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Otel) GetTraceSampleRate() float64 {
	if x != nil {
		return x.TraceSampleRate
	}
	return 0
}

func (x *Otel) GetMetricsEndpoint() string {
	if x != nil {
		return x.MetricsEndpoint
	}
	return ""
}

func (x *Otel) GetLogsEndpoint() string {
	if x != nil {
		return x.LogsEndpoint
	}
	return ""
}

func (x *Otel) GetMetricsIntervalSeconds() uint32 {
	if x != nil {
		return x.MetricsIntervalSeconds
	}
	return 0
}

// Data 数据层配置。
type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Db            *DB                    `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Redis         *Redis                 `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDb() *DB {
	if x != nil {
		return x.Db
	}
	return nil
}

func (x *Data) GetRedis() *Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

// DB MySQL 配置。
type DB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	DbName        string                 `protobuf:"bytes,5,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DB) Reset() {
	*x = DB{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DB) ProtoMessage() {}

func (x *DB) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DB.ProtoReflect.Descriptor instead.
func (*DB) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *DB) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DB) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DB) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DB) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DB) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

// Redis 缓存配置。
type Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redis) Reset() {
	*x = Redis{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redis) ProtoMessage() {}

func (x *Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redis.ProtoReflect.Descriptor instead.
func (*Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Redis) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Redis) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Server 服务端配置。
type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *HTTP                  `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Server) GetHttp() *HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

// HTTP HTTP 服务配置。
type HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Pprof         *Pprof                 `protobuf:"bytes,3,opt,name=pprof,proto3" json:"pprof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTP) Reset() {
	*x = HTTP{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTP) ProtoMessage() {}

func (x *HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTP.ProtoReflect.Descriptor instead.
func (*HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *HTTP) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HTTP) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HTTP) GetPprof() *Pprof {
	if x != nil {
		return x.Pprof
	}
	return nil
}

// Pprof 性能分析配置。
type Pprof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pprof) Reset() {
	*x = Pprof{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pprof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pprof) ProtoMessage() {}

func (x *Pprof) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pprof.ProtoReflect.Descriptor instead.
func (*Pprof) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Pprof) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Pprof) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Pprof) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Log 日志配置。
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`   // dev | prod
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // debug | info | warn | error
	Dir           string                 `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`     // 日志目录，留空则只输出到控制台
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *Log) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

// App 应用配置。
type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevMode       bool                   `protobuf:"varint,1,opt,name=dev_mode,json=devMode,proto3" json:"dev_mode,omitempty"`
	EnableDbDebug bool                   `protobuf:"varint,2,opt,name=enable_db_debug,json=enableDbDebug,proto3" json:"enable_db_debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *App) GetDevMode() bool {
	if x != nil {
		return x.DevMode
	}
	return false
}

func (x *App) GetEnableDbDebug() bool {
	if x != nil {
		return x.EnableDbDebug
	}
	return false
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\x04conf\"\xab\x01\n" +
	"\tBootstrap\x12\x1e\n" +
	"\x04data\x18\x01 \x01(\v2\n" +
	".conf.DataR\x04data\x12$\n" +
	"\x06server\x18\x02 \x01(\v2\f.conf.ServerR\x06server\x12\x1b\n" +
	"\x03log\x18\x03 \x01(\v2\t.conf.LogR\x03log\x12\x1b\n" +
	"\x03app\x18\x04 \x01(\v2\t.conf.AppR\x03app\x12\x1e\n" +
	"\x04otel\x18\x05 \x01(\v2\n" +
	".conf.OtelR\x04otel\"\xd1\x03\n" +
	"\x04Otel\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x1a\n" +
	"\binsecure\x18\x02 \x01(\bR\binsecure\x121\n" +
	"\aheaders\x18\x03 \x03(\v2\x17.conf.Otel.HeadersEntryR\aheaders\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_version\x18\x05 \x01(\tR\x0eserviceVersion\x12 \n" +
	"\venvironment\x18\x06 \x01(\tR\venvironment\x12*\n" +
	"\x11trace_sample_rate\x18\a \x01(\x01R\x0ftraceSampleRate\x12)\n" +
	"\x10metrics_endpoint\x18\b \x01(\tR\x0fmetricsEndpoint\x12#\n" +
	"\rlogs_endpoint\x18\t \x01(\tR\flogsEndpoint\x128\n" +
	"\x18metrics_interval_seconds\x18\n" +
	" \x01(\rR\x16metricsIntervalSeconds\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x04Data\x12\x18\n" +
	"\x02db\x18\x01 \x01(\v2\b.conf.DBR\x02db\x12!\n" +
	"\x05redis\x18\x02 \x01(\v2\v.conf.RedisR\x05redis\"u\n" +
	"\x02DB\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x17\n" +
	"\adb_name\x18\x05 \x01(\tR\x06dbName\"K\n" +
	"\x05Redis\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"(\n" +
	"\x06Server\x12\x1e\n" +
	"\x04http\x18\x01 \x01(\v2\n" +
	".conf.HTTPR\x04http\"Q\n" +
	"\x04HTTP\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12!\n" +
	"\x05pprof\x18\x03 \x01(\v2\v.conf.PprofR\x05pprof\"G\n" +
	"\x05Pprof\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"A\n" +
	"\x03Log\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\"H\n" +
	"\x03App\x12\x19\n" +
	"\bdev_mode\x18\x01 \x01(\bR\adevMode\x12&\n" +
	"\x0fenable_db_debug\x18\x02 \x01(\bR\renableDbDebugB!Z\x1fgin-template/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil), // 0: conf.Bootstrap
	(*Otel)(nil),      // 1: conf.Otel
	(*Data)(nil),      // 2: conf.Data
	(*DB)(nil),        // 3: conf.DB
	(*Redis)(nil),     // 4: conf.Redis
	(*Server)(nil),    // 5: conf.Server
	(*HTTP)(nil),      // 6: conf.HTTP
	(*Pprof)(nil),     // 7: conf.Pprof
	(*Log)(nil),       // 8: conf.Log
	(*App)(nil),       // 9: conf.App
	nil,               // 10: conf.Otel.HeadersEntry
}
var file_conf_conf_proto_depIdxs = []int32{
	2,  // 0: conf.Bootstrap.data:type_name -> conf.Data
	5,  // 1: conf.Bootstrap.server:type_name -> conf.Server
	8,  // 2: conf.Bootstrap.log:type_name -> conf.Log
	9,  // 3: conf.Bootstrap.app:type_name -> conf.App
	1,  // 4: conf.Bootstrap.otel:type_name -> conf.Otel
	10, // 5: conf.Otel.headers:type_name -> conf.Otel.HeadersEntry
	3,  // 6: conf.Data.db:type_name -> conf.DB
	4,  // 7: conf.Data.redis:type_name -> conf.Redis
	6,  // 8: conf.Server.http:type_name -> conf.HTTP
	7,  // 9: conf.HTTP.pprof:type_name -> conf.Pprof
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
